name: "Run tests via docker-compose"
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Run tests
      run: docker-compose run app sh -c "python manage.py test && flake8"
      